### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by ACGaming**

### CODE REVIEW

**Comment by Kittychanley** [comment]
TFC2 is only going to contain the English translation. Community translations for other languages should be done with resource packs posted on the forums.

**Comment by ACGaming** [comment]
So the final mod will only contain English?

**Comment by aliceingame** [comment]
As Kitty said, they decided not to include the translations in the official release of the mod.

However, when the first version is released (for not it look like there should be much more in that file), then I will most likely create a Google Drive document to do a group translation, and release a ressource pack that will include all the translations, so I will still be possible to play in any language, it will only require an extra step. I'll aslo see to put it on Curse, so it's easy to get the latest version in your Curse launcher if you use it.

**Comment by ACGaming** [comment]
Alright.

**Pull request closed without merging**
